// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {});

  // Height Match + Line height for header

  $("header .col-sm-6:first-child").height($("header .col-sm-6:last-child").height());
  var lineHeight =  $("header .col-sm-6:first-child").height;
  $("header .col-sm-6:first-child a").css('line-height', lineHeight + 'px');

   // Smooth Scrolling
  
  $(function() {
    $('a[href*=#]:not([href=#])').click(function() {
      if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
        var target = $(this.hash);
        target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
        if (target.length) {
          $('html,body').animate({
            scrollTop: target.offset().top-40
          }, 1000);
          return false;
        }
      }
    });
  });

  // Navigational class change on scroll
  
  var navpos = $('#navigation').offset();
    console.log(navpos.top);
      $(window).bind('scroll', function() {
        if ($(window).scrollTop() > navpos.top) {
          $('#navigation').addClass('nav-fixed');
         }
         else {
           $('#navigation').removeClass('nav-fixed');
         }
  });
  

}).call(this);
